-- =========================================
-- CityCare Hospital EMR
-- DATA ANALYSIS QUERIES (Client-Focused)
-- =========================================

USE CityCareHospital;

-- =====================================================
-- Q1: List all patients with their basic information
-- (Client wants to view all registered patients)
-- =====================================================
SELECT Patient_ID, First_Name, Last_Name, Gender, Phone
FROM Patient;

-- =====================================================
-- Q2: Show all doctors along with their specialties
-- (Client wants to know available doctors and expertise)
-- =====================================================
SELECT Doctor_ID, First_Name, Last_Name, Specialty
FROM Doctor;

-- =====================================================
-- Q3: Display all appointments with patient and doctor names
-- (Client wants a readable appointment schedule)
-- =====================================================
SELECT A.Appointment_ID,
       P.First_Name AS Patient_Name,
       D.First_Name AS Doctor_Name,
       A.Appointment_Date,
       A.Status
FROM Appointment A
JOIN Patient P ON A.Patient_ID = P.Patient_ID
JOIN Doctor D ON A.Doctor_ID = D.Doctor_ID;

-- =====================================================
-- Q4: Find all patients who have pending bills
-- (Client wants to track unpaid patients)
-- =====================================================
SELECT DISTINCT P.Patient_ID, P.First_Name, P.Last_Name
FROM Patient P
JOIN Billing B ON P.Patient_ID = B.Patient_ID
WHERE B.Payment_Status = 'Pending';

-- =====================================================
-- Q5: Show total revenue generated by the hospital
-- (Client wants financial summary)
-- =====================================================
SELECT SUM(Amount) AS Total_Revenue
FROM Billing;

-- =====================================================
-- Q6: List all lab tests along with patient names
-- (Client wants to review diagnostic activity)
-- =====================================================
SELECT L.Test_ID,
       P.First_Name,
       P.Last_Name,
       L.Test_Type,
       L.Test_Date
FROM Lab_Test L
JOIN Patient P ON L.Patient_ID = P.Patient_ID;

-- =====================================================
-- Q7: Find number of appointments handled by each doctor
-- (Client wants doctor workload analysis)
-- =====================================================
SELECT D.Doctor_ID,
       D.First_Name,
       COUNT(A.Appointment_ID) AS Total_Appointments
FROM Doctor D
LEFT JOIN Appointment A ON D.Doctor_ID = A.Doctor_ID
GROUP BY D.Doctor_ID, D.First_Name;

-- =====================================================
-- Q8: Show all medical records with patient and doctor names
-- (Client wants complete treatment history view)
-- =====================================================
SELECT M.Record_ID,
       P.First_Name AS Patient_Name,
       D.First_Name AS Doctor_Name,
       M.Diagnosis,
       M.Treatment,
       M.Visit_Date
FROM Medical_Record M
JOIN Patient P ON M.Patient_ID = P.Patient_ID
JOIN Doctor D ON M.Doctor_ID = D.Doctor_ID;

-- =====================================================
-- Q9: Find the most recent appointments (latest first)
-- (Client wants to monitor recent activity)
-- =====================================================
SELECT *
FROM Appointment
ORDER BY Appointment_Date DESC;

-- =====================================================
-- Q10: Find average billing amount per patient
-- (Client wants spending insights)
-- =====================================================
SELECT AVG(Amount) AS Average_Bill
FROM Billing;